'use strict'

app = angular.module('scApp', [ 'pouchdb' ])
app.controller 'MainCtrl', [
  '$scope'
  'pouchDB'
  ($scope, pouchDB) ->


    $scope.db = pouchDB('dbencomendas')

    $scope.db.changes(
      since: 'now'
      live: true).on 'change', testeshow

    $scope.addTodo = (text) ->
      todo =
        _id: (new Date).toISOString()
        title: text
        completed: false
      $scope.db.put todo, (err, result) ->
        if !err
          console.log 'DEU CERTO CARAI, O PUT.'
        return
      $scope.todoadd = todo
      return

    $scope.deletetodo = (id) ->
      $scope.db.remove id
      console.log id
      return


    testeshow = ->
      $scope.db.allDocs(
        include_docs: true
        descending: true).then((doc) ->
        $scope.teste = doc
        return
      ).catch (err) ->
        console.log err
        return
      return

    testeshow()
    return
]

# ---
# generated by js2coffee 2.1.0
